#XXX GENERATED BY generate_schema.pl
package  Wagayatei::DB::Schema;
use strict;
use warnings;


use Teng::Schema::Declare;
use Time::Piece::MySQL;
use JSON;

    table{
        name 'genre';
        pk qw (
        id
        );
        columns qw(
            name
            id
            name_en
        );
        row_class 'Wagayatei::Model::Genre';
    };
    table{
        name 'pc';
        pk qw (
        id
        );
        columns qw(
            profile
            status
            name
            sex
            uuid
            created_at
            updated_at
            id
            user_id
            type
            main_fg
            rank
        );
        inflate qr/_at$/ => sub {
            Time::Piece->from_mysql_datetime(shift);
        };
        deflate qr/_at$/ => sub {
            shift->mysql_datetime;
        };
        row_class 'Wagayatei::Model::Pc';
    };
    table{
        name 'pc_skill';
        pk qw (
        id
        );
        columns qw(
            skill_id
            uuid
            created_at
            updated_at
            pc_id
            id
            rank
        );
        inflate qr/_at$/ => sub {
            Time::Piece->from_mysql_datetime(shift);
        };
        deflate qr/_at$/ => sub {
            shift->mysql_datetime;
        };
        row_class 'Wagayatei::Model::PcSkill';
    };
    table{
        name 'skill';
        pk qw (
        id
        );
        columns qw(
            max
            name
            type_data
            uuid
            genre_id
            created_at
            updated_at
            id
        );
        inflate qr/_at$/ => sub {
            Time::Piece->from_mysql_datetime(shift);
        };
        deflate qr/_at$/ => sub {
            shift->mysql_datetime;
        };
        inflate qr/_data$/ => sub {
            JSON->new->utf8->decode(shift);
        };
        deflate qr/_data$/ => sub {
            JSON->new->utf8->encode(shift);
        };
        row_class 'Wagayatei::Model::Skill';
    };
    table{
        name 'user';
        pk qw (
        id
        );
        columns qw(
            status
            twitter_id
            name
            uuid
            token_secret
            created_at
            updated_at
            id
            token
            screen_name
        );
        inflate qr/_at$/ => sub {
            Time::Piece->from_mysql_datetime(shift);
        };
        deflate qr/_at$/ => sub {
            shift->mysql_datetime;
        };
        row_class 'Wagayatei::Model::User';
    };

1;
